-------create patients table from the ERD-------
CREATE TABLE IF NOT EXISTS public.patients
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default",
    date_of_birth date,
    CONSTRAINT patients_pkey PRIMARY KEY (id)
)

--------create treatments table ---------
CREATE TABLE IF NOT EXISTS public.treatments
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    type character varying COLLATE pg_catalog."default",
    name character varying COLLATE pg_catalog."default",
    CONSTRAINT treatments_pkey PRIMARY KEY (id)
)