-------create patients table from the ERD-------
CREATE TABLE IF NOT EXISTS public.patients
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default",
    date_of_birth date,
    CONSTRAINT patients_pkey PRIMARY KEY (id)
)

--------create treatments table ---------
CREATE TABLE IF NOT EXISTS public.treatments
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    type character varying COLLATE pg_catalog."default",
    name character varying COLLATE pg_catalog."default",
    CONSTRAINT treatments_pkey PRIMARY KEY (id)
)
--------create medical histories table -------
CREATE TABLE IF NOT EXISTS public.medical_histories
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    admitted_at timestamp with time zone,
    patient_id integer,
    CONSTRAINT medical_histories_pkey PRIMARY KEY (id),
    CONSTRAINT fk_medical_history_patients FOREIGN KEY (patient_id)
        REFERENCES public.patients (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

------------create medical_histories_treatments table many to many--------
CREATE TABLE IF NOT EXISTS public.medical_histories_treatments
(
    treatment_id integer,
    medical_history_id integer,
    CONSTRAINT fk_medical_hist_treat FOREIGN KEY (medical_history_id)
        REFERENCES public.medical_histories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_treat_hist_med FOREIGN KEY (treatment_id)
        REFERENCES public.treatments (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
------create invoices table -------------------------
CREATE TABLE IF NOT EXISTS public.invoices
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    total_amount numeric,
    generated_at timestamp with time zone,
    payed_at timestamp with time zone,
    medical_history_id integer,
    CONSTRAINT invoices_pkey PRIMARY KEY (id),
    CONSTRAINT fk_invoices_medical_his FOREIGN KEY (medical_history_id)
        REFERENCES public.medical_histories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
---------create invoice_items table-------
CREATE TABLE IF NOT EXISTS public.invoice_items
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    unit_price numeric,
    quantity integer,
    total_price numeric,
    invoice_id integer,
    treatment_id integer,
    CONSTRAINT invoice_items_pkey PRIMARY KEY (id),
    CONSTRAINT fk_invoice_items_invoice FOREIGN KEY (invoice_id)
        REFERENCES public.invoices (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_invoice_items_treatement FOREIGN KEY (treatment_id)
        REFERENCES public.treatments (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
